//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopSWE.Models.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int ID { get; set; }
        public string BannerTrai { get; set; }
        public string BannerPhai { get; set; }
        public string LinkFacebook { get; set; }
        public string LinkIsta { get; set; }
    }
}
